#pragma once

#include "core/types.hpp"
#include "core/plant.hpp"
#include <vector>

namespace pbg {

class World;

// Result of resource tick for debugging/visualization
struct ResourceTickResult {
    float energy_generated = 0.0f;
    float water_extracted = 0.0f;
    float nutrients_extracted = 0.0f;
    float energy_maintenance = 0.0f;
    float water_maintenance = 0.0f;
    float nutrients_maintenance = 0.0f;
    float net_energy = 0.0f;
    float net_water = 0.0f;
    float net_nutrients = 0.0f;
};

class ResourceSystem {
public:
    // Process one tick of resource flow for a plant
    // Returns detailed results for debugging
    static ResourceTickResult process_tick(Plant& plant, World& world);

    // Calculate energy generated by leaves
    static float calculate_leaf_energy(const Plant& plant, const World& world);

    // Calculate water extracted by roots
    static float calculate_root_water(const Plant& plant, World& world);

    // Calculate nutrients extracted by roots
    static float calculate_root_nutrients(const Plant& plant, World& world);

    // Calculate total maintenance costs
    static Resources calculate_maintenance(const Plant& plant);

    // Calculate resource storage caps based on store cells
    static Resources calculate_caps(const Plant& plant);

    // Clamp plant resources to their caps
    static void clamp_to_caps(Plant& plant);
};

}  // namespace pbg
