#pragma once

#include "core/types.hpp"
#include "core/plant.hpp"
#include <vector>
#include <unordered_map>

namespace pbg {

class World;

// Tracks resources at each cell during flow calculation
struct CellResources {
    float energy = 0.0f;
    float water = 0.0f;
    float nutrients = 0.0f;
};

// Result of resource tick for debugging/visualization
struct ResourceTickResult {
    float energy_generated = 0.0f;
    float water_extracted = 0.0f;
    float nutrients_extracted = 0.0f;
    float energy_maintenance = 0.0f;
    float water_maintenance = 0.0f;
    float nutrients_maintenance = 0.0f;
    float xylem_transfer_loss = 0.0f;
    float net_energy = 0.0f;
    float net_water = 0.0f;
    float net_nutrients = 0.0f;
};

class ResourceSystem {
public:
    // Process one tick of resource flow for a plant
    // Returns detailed results for debugging
    static ResourceTickResult process_tick(Plant& plant, World& world);

    // Calculate energy generated by leaves
    static float calculate_leaf_energy(const Plant& plant, const World& world);

    // Calculate water extracted by roots
    static float calculate_root_water(const Plant& plant, World& world);

    // Calculate nutrients extracted by roots
    static float calculate_root_nutrients(const Plant& plant, World& world);

    // Calculate total maintenance costs
    static Resources calculate_maintenance(const Plant& plant);

    // Process xylem flow - moves resources toward primary cell
    // Returns total resources that reached primary cell
    static Resources process_xylem_flow(Plant& plant, World& world);

private:
    // Build adjacency graph of plant cells
    static std::unordered_map<GridCoord, std::vector<GridCoord>>
        build_adjacency_graph(const Plant& plant);

    // Find path from cell to primary using BFS
    static std::vector<GridCoord> find_path_to_primary(
        const GridCoord& start,
        const GridCoord& primary,
        const std::unordered_map<GridCoord, std::vector<GridCoord>>& adj);
};

}  // namespace pbg
